### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by gaearon** [gaearon/flux-hot-loader#1]
## Pre 1.0

- [x] Get it working
- [x] Figure out if we can infer dispatchToken without requiring that you assign it
- [x] See if we can support several `register` calls per store
- [ ] Predictable/recoverable error handling story (what happens if new version error'd?)
- [ ] Make sure we don't screw up when error is sync inside module definition
- [ ] Emit changes in a batch
- [ ] Support ES6 exports
- [ ] Extract common code with react-hot-loader
- [ ] Refactor to avoid polluting dispatcher, `module.hot`
- [ ] Boilerplate project with react-router
- [ ] Document React Hot Loader manual mode (waits for React Router 0.12)
- [ ] Will it get slow if there are too many actions? What do we do?
- [ ] Give it some real world usage & get some feedback

## Post 1.0

- [ ] Figure out how we can adapt this to non-FB Flux implementations
- [ ] Anything else?

**Comment by gaearon** [comment]
@mjackson Waiting for RR 0.12 here :-)
